spring:
  application:
    name: BumaView
  config:
    import: optional:file:.env[.properties]
  
  datasource:
    url: jdbc:postgresql://localhost:5432/bumaview
    username: bumaview_user
    password: userpassword
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890
      expiration: 86400000
    password:
      bcrypt-strength: 12